export const GET_REPOS_REQUEST = 'GET_REPOS_REQUEST';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
export const GET_REPOS_ERROR = 'GET_REPOS_ERROR';

export const GET_REPO_REQUEST = 'GET_REPO_REQUEST';
export const GET_REPO_SUCCESS = 'GET_REPO_SUCCESS';
export const GET_REPO_ERROR = 'GET_REPO_ERROR';

export const GET_REPO_BRANCHES_REQUEST = 'GET_REPO_BRANCHES_REQUEST';
export const GET_REPO_BRANCHES_SUCCESS = 'GET_REPO_BRANCHES_SUCCESS';
export const GET_REPO_BRANCHES_ERROR = 'GET_REPO_BRANCHES_ERROR';

export const GET_REPO_COMMITS_REQUEST = 'GET_REPO_COMMITS_REQUEST';
export const GET_REPO_COMMITS_SUCCESS = 'GET_REPO_COMMITS_SUCCESS';
export const GET_REPO_COMMITS_ERROR = 'GET_REPO_COMMITS_ERROR';

export const GET_REPO_README_REQUEST = 'GET_REPO_README_REQUEST';
export const GET_REPO_README_SUCCESS = 'GET_REPO_README_SUCCESS';
export const GET_REPO_README_ERROR = 'GET_REPO_README_ERROR';